// <auto-generated />
using System;
using FindMyFamilyDoc.Business;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FindMyFamilyDoc.Business.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230529193716_AddingUserIdToDoctorTable")]
    partial class AddingUserIdToDoctorTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FindMyFamilyDoc.Shared.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9205),
                            CreatedBy = "System",
                            Name = "Toronto",
                            StateId = 7,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9208),
                            CreatedBy = "System",
                            Name = "Ottawa",
                            StateId = 7,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9209),
                            CreatedBy = "System",
                            Name = "Mississauga",
                            StateId = 7,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9211),
                            CreatedBy = "System",
                            Name = "Brampton",
                            StateId = 7,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9213),
                            CreatedBy = "System",
                            Name = "Hamilton",
                            StateId = 7,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9214),
                            CreatedBy = "System",
                            Name = "London",
                            StateId = 7,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9216),
                            CreatedBy = "System",
                            Name = "Markham",
                            StateId = 7,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9218),
                            CreatedBy = "System",
                            Name = "Vaughan",
                            StateId = 7,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9219),
                            CreatedBy = "System",
                            Name = "Kitchener",
                            StateId = 7,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9221),
                            CreatedBy = "System",
                            Name = "Windsor",
                            StateId = 7,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9223),
                            CreatedBy = "System",
                            Name = "Richmond Hill",
                            StateId = 7,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9225),
                            CreatedBy = "System",
                            Name = "Oakville",
                            StateId = 7,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9226),
                            CreatedBy = "System",
                            Name = "Burlington",
                            StateId = 7,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9228),
                            CreatedBy = "System",
                            Name = "Greater Sudbury",
                            StateId = 7,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9230),
                            CreatedBy = "System",
                            Name = "Waterloo",
                            StateId = 7,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9232),
                            CreatedBy = "System",
                            Name = "Oshawa",
                            StateId = 7,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9234),
                            CreatedBy = "System",
                            Name = "Barrie",
                            StateId = 7,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9235),
                            CreatedBy = "System",
                            Name = "Kingston",
                            StateId = 7,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9237),
                            CreatedBy = "System",
                            Name = "Guelph",
                            StateId = 7,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9239),
                            CreatedBy = "System",
                            Name = "Thunder Bay",
                            StateId = 7,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9258),
                            CreatedBy = "System",
                            Name = "Calgary",
                            StateId = 1,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9260),
                            CreatedBy = "System",
                            Name = "Edmonton",
                            StateId = 1,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9262),
                            CreatedBy = "System",
                            Name = "Red Deer",
                            StateId = 1,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9263),
                            CreatedBy = "System",
                            Name = "Lethbridge",
                            StateId = 1,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9265),
                            CreatedBy = "System",
                            Name = "St. Albert",
                            StateId = 1,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9275),
                            CreatedBy = "System",
                            Name = "Montreal",
                            StateId = 9,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9277),
                            CreatedBy = "System",
                            Name = "Quebec City",
                            StateId = 9,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9279),
                            CreatedBy = "System",
                            Name = "Laval",
                            StateId = 9,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9281),
                            CreatedBy = "System",
                            Name = "Gatineau",
                            StateId = 9,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9282),
                            CreatedBy = "System",
                            Name = "Longueuil",
                            StateId = 9,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9291),
                            CreatedBy = "System",
                            Name = "Moncton",
                            StateId = 4,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9293),
                            CreatedBy = "System",
                            Name = "Saint John",
                            StateId = 4,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9296),
                            CreatedBy = "System",
                            Name = "Fredericton",
                            StateId = 4,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9298),
                            CreatedBy = "System",
                            Name = "Dieppe",
                            StateId = 4,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9299),
                            CreatedBy = "System",
                            Name = "Riverview",
                            StateId = 4,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9309),
                            CreatedBy = "System",
                            Name = "Winnipeg",
                            StateId = 3,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9311),
                            CreatedBy = "System",
                            Name = "Brandon",
                            StateId = 3,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9313),
                            CreatedBy = "System",
                            Name = "Steinbach",
                            StateId = 3,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9315),
                            CreatedBy = "System",
                            Name = "Thompson",
                            StateId = 3,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9317),
                            CreatedBy = "System",
                            Name = "Portage la Prairie",
                            StateId = 3,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9325),
                            CreatedBy = "System",
                            Name = "St. John's",
                            StateId = 5,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9327),
                            CreatedBy = "System",
                            Name = "Mount Pearl",
                            StateId = 5,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9329),
                            CreatedBy = "System",
                            Name = "Conception Bay South",
                            StateId = 5,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9331),
                            CreatedBy = "System",
                            Name = "Paradise",
                            StateId = 5,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9332),
                            CreatedBy = "System",
                            Name = "Corner Brook",
                            StateId = 5,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9341),
                            CreatedBy = "System",
                            Name = "Halifax",
                            StateId = 6,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9343),
                            CreatedBy = "System",
                            Name = "Sydney",
                            StateId = 6,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9345),
                            CreatedBy = "System",
                            Name = "Truro",
                            StateId = 6,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9347),
                            CreatedBy = "System",
                            Name = "New Glasgow",
                            StateId = 6,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9348),
                            CreatedBy = "System",
                            Name = "Glace Bay",
                            StateId = 6,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("FindMyFamilyDoc.Shared.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactInformation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Fees")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsAcceptingNewPatients")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ProfilePicture")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("WaitingTime")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("FindMyFamilyDoc.Shared.Models.DoctorEducationBackground", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FieldOfStudy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstitutionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.ToTable("DoctorEducationBackgrounds");
                });

            modelBuilder.Entity("FindMyFamilyDoc.Shared.Models.DoctorExperience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.ToTable("Experiences");
                });

            modelBuilder.Entity("FindMyFamilyDoc.Shared.Models.DoctorLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("LanguageId");

                    b.ToTable("DoctorLanguages");
                });

            modelBuilder.Entity("FindMyFamilyDoc.Shared.Models.DoctorSpecialty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("SpecialtyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("SpecialtyId");

                    b.ToTable("DoctorSpecialties");
                });

            modelBuilder.Entity("FindMyFamilyDoc.Shared.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Language");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9397),
                            CreatedBy = "System",
                            Name = "English",
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9424),
                            CreatedBy = "System",
                            Name = "Spanish",
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9426),
                            CreatedBy = "System",
                            Name = "French",
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9427),
                            CreatedBy = "System",
                            Name = "German",
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9429),
                            CreatedBy = "System",
                            Name = "Italian",
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9431),
                            CreatedBy = "System",
                            Name = "Dutch",
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9432),
                            CreatedBy = "System",
                            Name = "Russian",
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9434),
                            CreatedBy = "System",
                            Name = "Chinese",
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9437),
                            CreatedBy = "System",
                            Name = "Japanese",
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9438),
                            CreatedBy = "System",
                            Name = "Korean",
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9440),
                            CreatedBy = "System",
                            Name = "Portuguese",
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9442),
                            CreatedBy = "System",
                            Name = "Arabic",
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9443),
                            CreatedBy = "System",
                            Name = "Swedish",
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9445),
                            CreatedBy = "System",
                            Name = "Danish",
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9446),
                            CreatedBy = "System",
                            Name = "Finnish",
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9448),
                            CreatedBy = "System",
                            Name = "Norwegian",
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9450),
                            CreatedBy = "System",
                            Name = "Polish",
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9452),
                            CreatedBy = "System",
                            Name = "Hungarian",
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9453),
                            CreatedBy = "System",
                            Name = "Greek",
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9455),
                            CreatedBy = "System",
                            Name = "Hebrew",
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9456),
                            CreatedBy = "System",
                            Name = "Turkish",
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9459),
                            CreatedBy = "System",
                            Name = "Hindi",
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9461),
                            CreatedBy = "System",
                            Name = "Bengali",
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9462),
                            CreatedBy = "System",
                            Name = "Urdu",
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9464),
                            CreatedBy = "System",
                            Name = "Punjabi",
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("FindMyFamilyDoc.Shared.Models.Specialty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Specialties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9368),
                            CreatedBy = "System",
                            Name = "Allergists/Immunologists",
                            Status = 0,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9370),
                            CreatedBy = "System",
                            Name = "Anesthesiologists",
                            Status = 0,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9372),
                            CreatedBy = "System",
                            Name = "Cardiologists",
                            Status = 0,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9373),
                            CreatedBy = "System",
                            Name = "Family and General Practitioners",
                            Status = 0,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9375),
                            CreatedBy = "System",
                            Name = "Neurologists",
                            Status = 0,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("FindMyFamilyDoc.Shared.Models.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("States");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9060),
                            CreatedBy = "System",
                            Name = "Alberta",
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9117),
                            CreatedBy = "System",
                            Name = "British Columbia",
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9120),
                            CreatedBy = "System",
                            Name = "Manitoba",
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9122),
                            CreatedBy = "System",
                            Name = "New Brunswick",
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9123),
                            CreatedBy = "System",
                            Name = "Newfoundland and Labrador",
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9125),
                            CreatedBy = "System",
                            Name = "Nova Scotia",
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9126),
                            CreatedBy = "System",
                            Name = "Ontario",
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9128),
                            CreatedBy = "System",
                            Name = "Prince Edward Island",
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9131),
                            CreatedBy = "System",
                            Name = "Quebec",
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9132),
                            CreatedBy = "System",
                            Name = "Saskatchewan",
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9134),
                            CreatedBy = "System",
                            Name = "Northwest Territories",
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9135),
                            CreatedBy = "System",
                            Name = "Nunavut",
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2023, 5, 29, 15, 37, 16, 10, DateTimeKind.Local).AddTicks(9137),
                            CreatedBy = "System",
                            Name = "Yukon",
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("FindMyFamilyDoc.Shared.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("FindMyFamilyDoc.Shared.Models.UserRefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserRefreshTokens");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "a1959f18-aa2d-4183-824c-b6cfc7323304",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "215c7543-fc5a-4c28-9791-5b1e0b39774a",
                            Name = "Doctor",
                            NormalizedName = "DOCTOR"
                        },
                        new
                        {
                            Id = "a767556d-fd18-45b8-b7e3-6f1f99fa42f0",
                            Name = "Patience",
                            NormalizedName = "PATIENCE"
                        },
                        new
                        {
                            Id = "05db3c49-7fbd-475a-9cc9-45c969d9c0c7",
                            Name = "AdministractiveAssistant",
                            NormalizedName = "ADMINISTRACTIVEASSISTANT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FindMyFamilyDoc.Shared.Models.City", b =>
                {
                    b.HasOne("FindMyFamilyDoc.Shared.Models.State", "State")
                        .WithMany("Cities")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("FindMyFamilyDoc.Shared.Models.Doctor", b =>
                {
                    b.HasOne("FindMyFamilyDoc.Shared.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FindMyFamilyDoc.Shared.Models.DoctorEducationBackground", b =>
                {
                    b.HasOne("FindMyFamilyDoc.Shared.Models.Doctor", "Doctor")
                        .WithMany("DoctorEducationBackgrounds")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("FindMyFamilyDoc.Shared.Models.DoctorExperience", b =>
                {
                    b.HasOne("FindMyFamilyDoc.Shared.Models.Doctor", "Doctor")
                        .WithMany("Experiences")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("FindMyFamilyDoc.Shared.Models.DoctorLanguage", b =>
                {
                    b.HasOne("FindMyFamilyDoc.Shared.Models.Doctor", "Doctor")
                        .WithMany("DoctorLanguages")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FindMyFamilyDoc.Shared.Models.Language", "Language")
                        .WithMany("DoctorLanguages")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("FindMyFamilyDoc.Shared.Models.DoctorSpecialty", b =>
                {
                    b.HasOne("FindMyFamilyDoc.Shared.Models.Doctor", "Doctor")
                        .WithMany("DoctorSpecialties")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FindMyFamilyDoc.Shared.Models.Specialty", "Specialty")
                        .WithMany("DoctorSpecialties")
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("FindMyFamilyDoc.Shared.Models.UserRefreshToken", b =>
                {
                    b.HasOne("FindMyFamilyDoc.Shared.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FindMyFamilyDoc.Shared.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FindMyFamilyDoc.Shared.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FindMyFamilyDoc.Shared.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FindMyFamilyDoc.Shared.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FindMyFamilyDoc.Shared.Models.Doctor", b =>
                {
                    b.Navigation("DoctorEducationBackgrounds");

                    b.Navigation("DoctorLanguages");

                    b.Navigation("DoctorSpecialties");

                    b.Navigation("Experiences");
                });

            modelBuilder.Entity("FindMyFamilyDoc.Shared.Models.Language", b =>
                {
                    b.Navigation("DoctorLanguages");
                });

            modelBuilder.Entity("FindMyFamilyDoc.Shared.Models.Specialty", b =>
                {
                    b.Navigation("DoctorSpecialties");
                });

            modelBuilder.Entity("FindMyFamilyDoc.Shared.Models.State", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
